# Generated by Django 4.1.1 on 2022-10-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in stock', 'in stock'), ('on order', 'on order'), ('expected', 'expected to arrive'), ('out of stock', 'out of stock'), ('not produced', 'not produced')], default='in stock', max_length=20, verbose_name='status'),
        ),
    ]
