# Generated by Django 4.1.1 on 2022-10-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'in stock'), ('on_order', 'on order'), ('expected', 'expected to arrive'), ('out_of_stock', 'out of stock'), ('not_produced', 'not produced')], default='in_stock', max_length=20, verbose_name='status'),
        ),
    ]
